<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- NuGet package metadata -->
    <PackageId>Fredagsbar.Shared</PackageId>
    <Version>0.0.1</Version>
    <Authors>PausedMagician,</Authors>
    <Description>Shared classes and DTOs for internal use</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
